### ISSUE TITLE
Reboot after Wifi connection

### ISSUE THREAD

**Issue by Prop3r** [guillaumef/cg-scale-wifi-oled#2]
Bonjour Guillaume,

Thank you for the excellent work and documentation on this CG scale. I'm in the final phase of building the scale, but I'm stuck. 

After turning on the device, the splash screen is shown, and after that the instructions to connect to the Wi-Fi appear. 
Every time I connect to the Wi-Fi, using my mobile phone, the scale reboots automatically. 

I've checked the wiring and boards for continuity and errors, and renewed the scale boards as a precaution, but to no avail. 

I've changed the 3,3V connection to the scale boards to 5V. No effect. Main power is provided by a 850mAh 1S lipo (4V).

Do you have any idea what could be wrong? 
Is there a log file somewhere I could check?

Cordialement,

Vincent

**Comment by guillaumef** [comment]
Bonjour Vincent,

Utilisez-vous la même board que celle que j'ai utilisé?
A mon sens, le problème doit se situer dans le soft et non le hard.
Le Wifi softAP est capricieux, ligne 369-370 - nombreux bugs sont remontés notamment sur les timings.
Essayer d'inserer en ligne 368:
```
    delay(1000);     
    WiFi.mode(WIFI_AP);
    delay(1000);  
    WiFi.persistent(false); 
```

**Comment by Prop3r** [comment]
Bonjour Guillaume,

Oui, je Utilisez le ESP32 OLED V2.0 TTGO. 

I will try your suggestion, thanks for the quick response!

Cordialement,

Vincent

**Comment by Prop3r** [comment]
Bonjour Guillaume,

I was able to successfully connect to the Wifi, without reboots. Thank you!

I could however not connect to the webpage http://172.16.19.1/
After checking the code, I noticed a small error: 

IPAddress local_IP(172,16,9,1);
IPAddress gateway(172,16,9,1);

This should be: 
IPAddress local_IP(172,16,19,1);
IPAddress gateway(172,16,19,1);

All works now!

Cordialement, 

Vincent

**Comment by guillaumef** [comment]
Great. I hope you will find it accurate. My two builds are working perfectly (I made a second one with two throw meters and a detachable rj45 cable).

**Comment by lanceDee** [comment]
@Prop3r  hi vincent,

I just started to make a cg scale for my F3K planes, but I got the same issue as you did - When wifi connected and I tried to access the web page, it crahes. Wondering how did you resolve the issue?

And greetings to @guillaumef , thanks for the great project. I'm not sure if you're still maintaining this, I do appreciate it if you can give me some suggestions:
I'm using a ESP8266 and I modified the head files Wifi.h and WifiAp.h to ESP8266Wifi.h and ESP8266WifiAp.h and built without errors or warnings. I use vscode + platformio plugin, and I enabled the flag monitor_filters = esp8266_exception_decoder, saw that the error was about a ethernet function:
--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Exception (3):
epc1=0x4000dfb4 epc2=0x00000000 epc3=0x00000000 excvaddr=0x40242abc depc=0x00000000

LoadStoreError: Processor internal physical address or data error during load or store
  excvaddr=0x40242abc in ethernet_input at ??:?

It seems to be triggered by ui.update() in loop() function. So I wonder if it has something to do with my OLED setting. I connected the esp8266 board to my PC directly, and no OLED module connected ( I just want to see if it works before I solder the OLED).
